title: Highlight Content
status: wip
context:
  section-header:
    headline: "Highlight Content"
    text: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren."

  data-slider-highlight-content:
    - image: "/images/gemasolar-fuentes-de-andalucia-andalousie-espagne-photo-01.png"
      preline: "Taxonomie Contenttyp"
      headline: "Nulla luctus pharetra vulputate tells mollis orci sed rhoncus"
      copy: "Consectetur adipisifwcing elit, sed eiusmod tempor incididunt ut labore et dolore."
      highlight: true

    - preline: "Taxonomie Contenttyp"
      headline: "Nulla luctus pharetra vulputate tells mollis orci sed rhoncus"
      copy: "Consectetur adipisifwcing elit, sed eiusmod tempor incididunt ut labore et dolore."
      highlight: false

    - image: "/images/pexels-photo-2101135.png"
      preline: "Taxonomie Contenttyp"
      headline: "Nulla luctus pharetra vulputate tells mollis orci sed rhoncus"
      copy: "Consectetur adipisifwcing elit, sed eiusmod tempor incididunt ut labore et dolore."
      highlight: false

    - image: "/images/Bild 33@2x.png"
      preline: "Taxonomie Contenttyp"
      headline: "Nulla luctus pharetra vulputate tells mollis orci sed rhoncus"
      copy: "Consectetur adipisifwcing elit, sed eiusmod tempor incididunt ut labore et dolore."
      highlight: false
