title: Highlight Content
status: wip
context:
  section-header:
    headline: "Highlight Content"
    text: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren."

  card-default--highlight:
    Image: "/images/gemasolar-fuentes-de-andalucia-andalousie-espagne-photo-01.png"
    Preline: "this is a Preline"
    Headline: "I am the Headline"
    Copy: "Copy / Body text Lorem Ipsum some more text."

  card-default--text:
    Preline: "this is a Preline"
    Headline: "I am the Headline"
    Copy: "Copy / Body text Lorem Ipsum some more text."

  card-default:
    Image: "/images/gemasolar-fuentes-de-andalucia-andalousie-espagne-photo-01.png"
    Preline: "this is a Preline"
    Headline: "I am the Headline"
    Copy: "Copy / Body text Lorem Ipsum some more text."
