title: Card
status: wip

context:
  card-default:
    image: "/images/gemasolar-fuentes-de-andalucia-andalousie-espagne-photo-01.png"
    preline: "this is a Preline"
    headline: "I am the Headline"
    copy: "Copy / Body text Lorem Ipsum some more text."
  card-default--highlight:
    image: "/images/gemasolar-fuentes-de-andalucia-andalousie-espagne-photo-01.png"
    preline: "this is a Preline"
    headline: "I am the Headline"
    copy: "Copy / Body text Lorem Ipsum some more text."
  card-default--text:
    preline: "this is a Preline"
    headline: "I am the Headline"
    copy: "Copy / Body text Lorem Ipsum some more text."
