title: Card
status: wip

variants:
  - name: "Highlight + Img"
    context:
      image: "/images/gemasolar-fuentes-de-andalucia-andalousie-espagne-photo-01.png"
      preline: "Taxonomie Contenttyp"
      headline: "I am the Headline"
      copy: "Copy / Body text Lorem Ipsum some more text."
      highlight: true

  - name: "default"
    context:
      image: "/images/gemasolar-fuentes-de-andalucia-andalousie-espagne-photo-01.png"
      preline: "Taxonomie Contenttyp"
      headline: "I am the Headline"
      copy: "Copy / Body text Lorem Ipsum some more text."
      highlight: false

  - name: "No img"
    context:
      preline: "Taxonomie Contenttyp"
      headline: "I am the Headline"
      copy: "Copy / Body text Lorem Ipsum some more text."
      highlight: false
