title: Card-Facts
status: wip

variants:
  - name: default
    context:
      card-facts:
        copy: "3,51 Prozent Durchschnittliches Wachstum afrikanischer Volkswirtschaften in 2018"
        number: "3,5"
        color: "primary"

  - name: secondary
    context:
      card-facts:
        color: "secondary"
        number: "10"
        copy: "3,5 Prozent Durchschnittliches Wachstum afrikanischer Volkswirtschaften in 2018"

  - name: ocean
    context:
      card-facts:
        color: "ocean"
        number: "100"
        copy: "3,5 Prozent Durchschnittliches Wachstum afrikanischer Volkswirtschaften in 2018"

  - name: coffee
    context:
      card-facts:
        color: "coffee"
        number: "0,1"
        copy: "3,5 Prozent Durchschnittliches Wachstum afrikanischer Volkswirtschaften in 2018"
